version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: todos_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  

  server:
    image: sammmmmm/node-app:1.0
    build:
      context: ./server
    restart: always
    environment:
      DB_USER: user
      DB_HOST: db
      DB_NAME: todos_db
      DB_PASSWORD: password
      DB_PORT: 5432
      PORT: 4002
    depends_on:
      - db
    ports:
      - "4002:4002"  

  client:
    image: sammmmmm/react-app:1.0
    build:
      context: ./client
    restart: always
    ports:
      - "4001:4001"
    depends_on:
      - server

volumes:
  postgres_data:
