name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
         - name: Checkout repository
           uses: actions/checkout@v3

         - name: Setup Node.js
           uses: actions/setup-node@v3
           with:
             node-version: ${{ matrix.node-version }}
         
         - name: Install API dependencies
           run: npm install

         - name: Build API
           run: npm run build --if-present

         - name: Run unit tests
           run: npm run test:unit
        
         - name: Build Docker Image
           run: |
              docker build -t "${{ secrets.DOCKER_USERNAME }}"/node-api .

         - name: Run integration tests
           run: npm run test:integration

         - name: Log in => Docker Hub
           run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
   
         - name: Push Docker Image => Docker Hub
           run: |
             docker push "${{ secrets.DOCKER_USERNAME }}"/node-api:1.0
    